#!/bin/bash

if [[ -z "$GIT_DIR" ]]; then
	GIT_DIR="$(dirname "$(realpath "$0")")/../.git"
fi

cd "$GIT_DIR/.."

changes=$(git diff --name-only @{1} 2> /dev/null)
fresh_clone=$?

# Exit if nothing has changed
if [ ! $fresh_clone ] && [[ -z "$changes" ]]; then
	exit
fi

# Update databse
php index.php tools update_database

# Minify javascript
if echo "$changes" | grep data/js/ > /dev/null; then
	scripts/optimize_js.sh
fi

if [[ ! -f ./data/js/main.min.js ]]; then
	scripts/optimize_js.sh
fi

# Show changes to NEWS
git diff @{1} NEWS 2> /dev/null | cat
