#!/bin/sh
# Note: the highlight command (http://www.andre-simon.de/) uses css for syntax
# highlighting, so you'll probably want something like the following included
# in your css file (generated by highlight 2.4.8 and adapted for cgit):
#
# table.blob .num  { color:#2928ff; }
# table.blob .esc  { color:#ff00ff; }
# table.blob .str  { color:#ff0000; }
# table.blob .dstr { color:#818100; }
# table.blob .slc  { color:#838183; font-style:italic; }
# table.blob .com  { color:#838183; font-style:italic; }
# table.blob .dir  { color:#008200; }
# table.blob .sym  { color:#000000; }
# table.blob .kwa  { color:#000000; font-weight:bold; }
# table.blob .kwb  { color:#830000; }
# table.blob .kwc  { color:#000000; font-weight:bold; }
# table.blob .kwd  { color:#010181; }

case "$1" in
  *.4gl) exec /usr/bin/highlight -f -I -X -S 4gl;;
  *.a4c) exec /usr/bin/highlight -f -I -X -S a4c;;
  *.abp) exec /usr/bin/highlight -f -I -X -S abp;;
  *.ada) exec /usr/bin/highlight -f -I -X -S ada;;
  *.agda) exec /usr/bin/highlight -f -I -X -S agda;;
  *.ampl) exec /usr/bin/highlight -f -I -X -S ampl;;
  *.amtrix) exec /usr/bin/highlight -f -I -X -S amtrix;;
  *.applescript) exec /usr/bin/highlight -f -I -X -S applescript;;
  *.arc) exec /usr/bin/highlight -f -I -X -S arc;;
  *.arm) exec /usr/bin/highlight -f -I -X -S arm;;
  *.as) exec /usr/bin/highlight -f -I -X -S as;;
  *.asm) exec /usr/bin/highlight -f -I -X -S asm;;
  *.asp) exec /usr/bin/highlight -f -I -X -S asp;;
  *.aspect) exec /usr/bin/highlight -f -I -X -S aspect;;
  *.ats) exec /usr/bin/highlight -f -I -X -S ats;;
  *.au3) exec /usr/bin/highlight -f -I -X -S au3;;
  *.avenue) exec /usr/bin/highlight -f -I -X -S avenue;;
  *.awk) exec /usr/bin/highlight -f -I -X -S awk;;
  *.bat) exec /usr/bin/highlight -f -I -X -S bat;;
  *.bb) exec /usr/bin/highlight -f -I -X -S bb;;
  *.bib) exec /usr/bin/highlight -f -I -X -S bib;;
  *.bms) exec /usr/bin/highlight -f -I -X -S bms;;
  *.boo) exec /usr/bin/highlight -f -I -X -S boo;;
  *.c|*.h|*.cpp|*.C|*.H) exec /usr/bin/highlight -f -I -X -S c;;
  *.cb) exec /usr/bin/highlight -f -I -X -S cb;;
  *.cfc) exec /usr/bin/highlight -f -I -X -S cfc;;
  *.chl) exec /usr/bin/highlight -f -I -X -S chl;;
  *.clipper) exec /usr/bin/highlight -f -I -X -S clipper;;
  *.clojure) exec /usr/bin/highlight -f -I -X -S clojure;;
  *.clp) exec /usr/bin/highlight -f -I -X -S clp;;
  *.cob) exec /usr/bin/highlight -f -I -X -S cob;;
  *.cs) exec /usr/bin/highlight -f -I -X -S cs;;
  *.css) exec /usr/bin/highlight -f -I -X -S css;;
  *.d) exec /usr/bin/highlight -f -I -X -S d;;
  *.diff|*.patch) exec /usr/bin/highlight -f -I -X -S diff;;
  *.dot) exec /usr/bin/highlight -f -I -X -S dot;;
  *.dylan) exec /usr/bin/highlight -f -I -X -S dylan;;
  *.e) exec /usr/bin/highlight -f -I -X -S e;;
  *.erl) exec /usr/bin/highlight -f -I -X -S erl;;
  *.euphoria) exec /usr/bin/highlight -f -I -X -S euphoria;;
  *.exp) exec /usr/bin/highlight -f -I -X -S exp;;
  *.f77) exec /usr/bin/highlight -f -I -X -S f77;;
  *.f90) exec /usr/bin/highlight -f -I -X -S f90;;
  *.flx) exec /usr/bin/highlight -f -I -X -S flx;;
  *.frink) exec /usr/bin/highlight -f -I -X -S frink;;
  *.haskell|*.hs) exec /usr/bin/highlight -f -I -X -S haskell;;
  *.hcl) exec /usr/bin/highlight -f -I -X -S hcl;;
  *.httpd) exec /usr/bin/highlight -f -I -X -S httpd;;
  *.icn) exec /usr/bin/highlight -f -I -X -S icn;;
  *.idl) exec /usr/bin/highlight -f -I -X -S idl;;
  *.idlang) exec /usr/bin/highlight -f -I -X -S idlang;;
  *.ili) exec /usr/bin/highlight -f -I -X -S ili;;
  *.ini) exec /usr/bin/highlight -f -I -X -S ini;;
  *.inp) exec /usr/bin/highlight -f -I -X -S inp;;
  *.io) exec /usr/bin/highlight -f -I -X -S io;;
  *.iss) exec /usr/bin/highlight -f -I -X -S iss;;
  *.j) exec /usr/bin/highlight -f -I -X -S j;;
  *.java) exec /usr/bin/highlight -f -I -X -S java;;
  *.js) exec /usr/bin/highlight -f -I -X -S js;;
  *.jsp) exec /usr/bin/highlight -f -I -X -S jsp;;
  *.lbn) exec /usr/bin/highlight -f -I -X -S lbn;;
  *.ldif) exec /usr/bin/highlight -f -I -X -S ldif;;
  *.lgt) exec /usr/bin/highlight -f -I -X -S lgt;;
  *.lhs) exec /usr/bin/highlight -f -I -X -S lhs;;
  *.lisp) exec /usr/bin/highlight -f -I -X -S lisp;;
  *.lotos) exec /usr/bin/highlight -f -I -X -S lotos;;
  *.ls) exec /usr/bin/highlight -f -I -X -S ls;;
  *.lsl) exec /usr/bin/highlight -f -I -X -S lsl;;
  *.lua) exec /usr/bin/highlight -f -I -X -S lua;;
  *.ly) exec /usr/bin/highlight -f -I -X -S ly;;
  *.m) exec /usr/bin/highlight -f -I -X -S m;;
  *.make) exec /usr/bin/highlight -f -I -X -S make;;
  *.mel) exec /usr/bin/highlight -f -I -X -S mel;;
  *.mercury) exec /usr/bin/highlight -f -I -X -S mercury;;
  *.mib) exec /usr/bin/highlight -f -I -X -S mib;;
  *.miranda) exec /usr/bin/highlight -f -I -X -S miranda;;
  *.ml) exec /usr/bin/highlight -f -I -X -S ml;;
  *.mo) exec /usr/bin/highlight -f -I -X -S mo;;
  *.mod3) exec /usr/bin/highlight -f -I -X -S mod3;;
  *.mpl) exec /usr/bin/highlight -f -I -X -S mpl;;
  *.ms) exec /usr/bin/highlight -f -I -X -S ms;;
  *.mssql) exec /usr/bin/highlight -f -I -X -S mssql;;
  *.n) exec /usr/bin/highlight -f -I -X -S n;;
  *.nas) exec /usr/bin/highlight -f -I -X -S nas;;
  *.nice) exec /usr/bin/highlight -f -I -X -S nice;;
  *.nrx) exec /usr/bin/highlight -f -I -X -S nrx;;
  *.nsi) exec /usr/bin/highlight -f -I -X -S nsi;;
  *.nut) exec /usr/bin/highlight -f -I -X -S nut;;
  *.oberon) exec /usr/bin/highlight -f -I -X -S oberon;;
  *.objc) exec /usr/bin/highlight -f -I -X -S objc;;
  *.octave) exec /usr/bin/highlight -f -I -X -S octave;;
  *.oorexx) exec /usr/bin/highlight -f -I -X -S oorexx;;
  *.os) exec /usr/bin/highlight -f -I -X -S os;;
  *.oz) exec /usr/bin/highlight -f -I -X -S oz;;
  *.pas) exec /usr/bin/highlight -f -I -X -S pas;;
  *.php) exec /usr/bin/highlight -f -I -X -S php;;
  *.pike) exec /usr/bin/highlight -f -I -X -S pike;;
  *.pl|*.perl|*.pm) exec /usr/bin/highlight -f -I -X -S pl;;
  *.pl1) exec /usr/bin/highlight -f -I -X -S pl1;;
  *.pov) exec /usr/bin/highlight -f -I -X -S pov;;
  *.pro) exec /usr/bin/highlight -f -I -X -S pro;;
  *.progress) exec /usr/bin/highlight -f -I -X -S progress;;
  *.ps) exec /usr/bin/highlight -f -I -X -S ps;;
  *.ps1) exec /usr/bin/highlight -f -I -X -S ps1;;
  *.psl) exec /usr/bin/highlight -f -I -X -S psl;;
  *.py) exec /usr/bin/highlight -f -I -X -S py;;
  *.pyx) exec /usr/bin/highlight -f -I -X -S pyx;;
  *.q) exec /usr/bin/highlight -f -I -X -S q;;
  *.qmake) exec /usr/bin/highlight -f -I -X -S qmake;;
  *.qu) exec /usr/bin/highlight -f -I -X -S qu;;
  *.r) exec /usr/bin/highlight -f -I -X -S r;;
  *.rb) exec /usr/bin/highlight -f -I -X -S rb;;
  *.rebol) exec /usr/bin/highlight -f -I -X -S rebol;;
  *.rexx) exec /usr/bin/highlight -f -I -X -S rexx;;
  *.rnc) exec /usr/bin/highlight -f -I -X -S rnc;;
  *.s) exec /usr/bin/highlight -f -I -X -S s;;
  *.sas) exec /usr/bin/highlight -f -I -X -S sas;;
  *.sc) exec /usr/bin/highlight -f -I -X -S sc;;
  *.scala) exec /usr/bin/highlight -f -I -X -S scala;;
  *.scilab) exec /usr/bin/highlight -f -I -X -S scilab;;
  *.sh) exec /usr/bin/highlight -f -I -X -S sh;;
  *.sma) exec /usr/bin/highlight -f -I -X -S sma;;
  *.smalltalk) exec /usr/bin/highlight -f -I -X -S smalltalk;;
  *.sml) exec /usr/bin/highlight -f -I -X -S sml;;
  *.sno) exec /usr/bin/highlight -f -I -X -S sno;;
  *.spec) exec /usr/bin/highlight -f -I -X -S spec;;
  *.spn) exec /usr/bin/highlight -f -I -X -S spn;;
  *.sql) exec /usr/bin/highlight -f -I -X -S sql;;
  *.sybase) exec /usr/bin/highlight -f -I -X -S sybase;;
  *.tcl) exec /usr/bin/highlight -f -I -X -S tcl;;
  *.tcsh) exec /usr/bin/highlight -f -I -X -S tcsh;;
  *.test_re) exec /usr/bin/highlight -f -I -X -S test_re;;
  *.tex) exec /usr/bin/highlight -f -I -X -S tex;;
  *.ttcn3) exec /usr/bin/highlight -f -I -X -S ttcn3;;
  *.vala) exec /usr/bin/highlight -f -I -X -S vala;;
  *.vb) exec /usr/bin/highlight -f -I -X -S vb;;
  *.verilog) exec /usr/bin/highlight -f -I -X -S verilog;;
  *.vhd) exec /usr/bin/highlight -f -I -X -S vhd;;
  *.xml|*.htm|*.html) exec /usr/bin/highlight -f -I -X -S xml;;
  *.xpp) exec /usr/bin/highlight -f -I -X -S xpp;;
  *.y) exec /usr/bin/highlight -f -I -X -S y;;
  *.znn) exec /usr/bin/highlight -f -I -X -S znn;;
  *) exec /usr/bin/highlight -f -I -X -S txt;;
esac
